# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.3
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 65
Metrics/BlockLength:
  Max: 35
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 180
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Elegant/ClassInModule:
  Exclude:
    - 'lib/**/*'
    - '**/test_*.rb'
    - '**/*Test.rb'
Style/OptionalBooleanParameter:
  Enabled: false
Style/AutoResourceCleanup:
  Enabled: false
Style/FileOpen:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-elegant
