assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" futex.gemspec
    git add futex.gemspec
    git commit -m "Version set to ${tag}"
    gem build futex.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    bundle install
    rake
deploy: {}
