# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT

language: ruby
rvm:
  - 2.6.0
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
script:
  - bundle exec rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
